#!/bin/bash
CLAUDE="op://Api Keys/Anthropic API Key/credential"
OPENAI="op://Api Keys/OpenAI Platform/credential"
aider --dark-mode --anthropic-api-key $(op read "$CLAUDE") --openai-api-key $(op read "$OPENAI") \
  --editor-model o1-mini \
  --editor-edit-format whole \
  --model o1-preview \
  --edit-format whole \
  --architect
