#!/bin/bash
CLAUDE="op://Api Keys/Anthropic API Key/credential"
OPENAI="op://Api Keys/OpenAI Platform/credential"
aider --dark-mode --anthropic-api-key $(op read "$CLAUDE") --openai-api-key $(op read "$OPENAI") \
  --editor-model anthropic/claude-3-5-sonnet-20241022 \
  --model anthropic/claude-3-5-sonnet-20241022
